services:
  - type: web
    plan: free
    name: ToxicAutoFilterBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/SparkZHarrY/File-Sharing-Botz.git      
    branch: main
    envVars:
      - key: API_HASH
        sync: false
      - key: API_ID 
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: ADMINS
        sync: false
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_MESSAGE
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: PROTECT_CONTENT
        sync: false
      - key: FORCE_SUB_MESSAGE
        sync: false
    autoDeploy: true
